//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KofaxIndexRecon_OnBase.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KIRec_OB")]
        public string EventLogName {
            get {
                return ((string)(this["EventLogName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KIRec_OB")]
        public string EventSourceName {
            get {
                return ((string)(this["EventSourceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Exchange2013_SP1")]
        public string ExchangeVersion {
            get {
                return ((string)(this["ExchangeVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EWSUri {
            get {
                return ((string)(this["EWSUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("svs-dkfx-process@ncsecu.dev")]
        public string EmailFrom {
            get {
                return ((string)(this["EmailFrom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KofaxIndexRecon_OnBase has failed!")]
        public string EmailErrorSubject {
            get {
                return ((string)(this["EmailErrorSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("someone1@ncsecu.dev, someone2@ncsecu.dev")]
        public string EmailTo {
            get {
                return ((string)(this["EmailTo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DKFX0350,3314;Initial Catalog=Kofax_FormInfo;Integrated Security=SSPI" +
            "")]
        public string KofaxConnString {
            get {
                return ((string)(this["KofaxConnString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int DbCmdTimeout {
            get {
                return ((int)(this["DbCmdTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo.KfxIndxRconOB_SelectRecFromKofaxInfo")]
        public string SP_PopulateFormIdsToProcess {
            get {
                return ((string)(this["SP_PopulateFormIdsToProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NumDaysBeforeEmptyStatusScanned {
            get {
                return ((int)(this["NumDaysBeforeEmptyStatusScanned"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OnBase_MemdocRecords")]
        public string TableName_MemdocRecords {
            get {
                return ((string)(this["TableName_MemdocRecords"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FormIDs_To_Process")]
        public string TableName_KofaxRecords {
            get {
                return ((string)(this["TableName_KofaxRecords"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03-11-2020")]
        public string LastSuccessfullRun {
            get {
                return ((string)(this["LastSuccessfullRun"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Warning: KofaxIndexRecon_OnBase  encountered an issue")]
        public string EmailWarningSubject {
            get {
                return ((string)(this["EmailWarningSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KfxIndxRconOB_SelectRecFromOnBase")]
        public string SP_OnBaseFetching {
            get {
                return ((string)(this["SP_OnBaseFetching"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=7912W099;Initial Catalog=OnBaseHelper;Integrated Security=SSPI")]
        public string OnBaseConnString {
            get {
                return ((string)(this["OnBaseConnString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KfxIndxRconOB_TruncateTables")]
        public string SP_TruncateTables {
            get {
                return ((string)(this["SP_TruncateTables"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KfxIndxRcon_UpdtRecNotScanned")]
        public string SP_UpdateRecNotScanned {
            get {
                return ((string)(this["SP_UpdateRecNotScanned"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KfxIndxRconOB_UpdtRecScannedButMissingInOnBase")]
        public string SP_UpdtRecScannedButMissingInCMS {
            get {
                return ((string)(this["SP_UpdtRecScannedButMissingInCMS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KfxIndxRconOB_UpdateFormInfoTable")]
        public string SP_UpdateFormInfoTable {
            get {
                return ((string)(this["SP_UpdateFormInfoTable"]));
            }
        }
    }
}
