USE [master]
GO

CREATE DATABASE [OnBaseHelper]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OnBaseHelper', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLSERV2017DEV\MSSQL\DATA\OnBaseHelper.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OnBaseHelper_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLSERV2017DEV\MSSQL\DATA\OnBaseHelper_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [OnBaseHelper] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OnBaseHelper].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OnBaseHelper] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OnBaseHelper] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OnBaseHelper] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OnBaseHelper] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OnBaseHelper] SET ARITHABORT OFF 
GO

ALTER DATABASE [OnBaseHelper] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OnBaseHelper] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OnBaseHelper] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OnBaseHelper] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OnBaseHelper] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OnBaseHelper] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OnBaseHelper] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OnBaseHelper] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OnBaseHelper] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OnBaseHelper] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OnBaseHelper] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OnBaseHelper] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OnBaseHelper] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OnBaseHelper] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OnBaseHelper] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OnBaseHelper] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OnBaseHelper] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OnBaseHelper] SET RECOVERY FULL 
GO

ALTER DATABASE [OnBaseHelper] SET  MULTI_USER 
GO

ALTER DATABASE [OnBaseHelper] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OnBaseHelper] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OnBaseHelper] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OnBaseHelper] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OnBaseHelper] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OnBaseHelper] SET QUERY_STORE = OFF
GO

ALTER DATABASE [OnBaseHelper] SET  READ_WRITE 
GO
